#!/usr/bin/env python3
"""tgc: a tiny CUDA-style kernel language for TinyGPU v2.

A kernel is a C function marked __kernel whose body describes ONE element, indexed by `tid`
(1-D) or `tx`/`ty` (2-D, __kernel2d). tgc turns it into an ordinary C loop over the launch
range with restrict pointers and `#pragma GCC ivdep`; GCC (-O3, zve32f, zvl512b) then emits
RVV instructions that the CPU issues straight to the GPU. No driver, no runtime: a launch is
a function call.

    __kernel void saxpy(float a, const float *x, float *y) {
        y[tid] = a * x[tid] + y[tid];
    }
    ...
    launch(saxpy, n, 2.0f, x, y);              // y[0..n) = 2*x + y on the GPU
    launch2d(blend, w, h, dst, src, alpha);    // tx in [0,w), ty in [0,h)

Usage: tgc.py in.tgc -o out.c     (then compile out.c like any C file)
"""
import argparse
import re
import sys

HEADER = """/* generated by tgc from {src}: do not edit */
#include <stdint.h>
#define launch(k, n, ...)        k##__tgc((int)(n), __VA_ARGS__)
#define launch2d(k, w, h, ...)   k##__tgc((int)(w), (int)(h), __VA_ARGS__)
"""

KERNEL_RE = re.compile(r"__kernel(2d)?\s+void\s+(\w+)\s*\(([^)]*)\)\s*\{", re.S)


def restrict_params(params):
    out = []
    for p in [p.strip() for p in params.split(",") if p.strip()]:
        if "*" in p and "restrict" not in p:
            # T *name -> T *restrict name
            p = re.sub(r"\*\s*(\w+)\s*$", r"*restrict \1", p)
        out.append(p)
    return out


def match_brace(text, start):
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    raise SyntaxError("unbalanced braces in kernel")


def translate(src, name):
    out = [HEADER.format(src=name)]
    pos = 0
    for m in KERNEL_RE.finditer(src):
        out.append(src[pos:m.start()])
        two_d, kname, params = m.group(1), m.group(2), m.group(3)
        body_open = m.end() - 1
        body_close = match_brace(src, body_open)
        body = src[body_open + 1:body_close]
        ps = restrict_params(params)
        if two_d:
            sig = ", ".join(["int __w", "int __h"] + ps)
            loop = (f"    for (int ty = 0; ty < __h; ty++) {{\n"
                    f"#pragma GCC ivdep\n"
                    f"        for (int tx = 0; tx < __w; tx++) {{{body}}}\n"
                    f"    }}\n")
        else:
            sig = ", ".join(["int __n"] + ps)
            loop = (f"#pragma GCC ivdep\n"
                    f"    for (int tid = 0; tid < __n; tid++) {{{body}}}\n")
        out.append(f"void {kname}__tgc({sig})\n{{\n{loop}}}\n")
        pos = body_close + 1
    out.append(src[pos:])
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input")
    ap.add_argument("-o", "--output", required=True)
    a = ap.parse_args()
    src = open(a.input).read()
    try:
        c = translate(src, a.input)
    except SyntaxError as e:
        sys.exit(f"tgc: {a.input}: {e}")
    with open(a.output, "w") as f:
        f.write(c)


if __name__ == "__main__":
    main()
