#!/usr/bin/env python3
"""Run riscv-tests and random vector tests on the ZC702 board over JTAG.

    board_tests.py prepare [--seeds 0-24] [--classes int,mask,...] [--irq-seeds 0-24]
    board_tests.py check

prepare builds every image (riscv-tests from RISCV_TESTS_DIR, vector tests from vgen.py with
Spike reference signatures) into OUT (default D:/ScratchGPU_Vivado/board_tests) and writes
manifest.tcl. D:/ScratchGPU_Vivado/run_board_tests.tcl then loads each image into DDR, releases
Synapse from reset, polls tohost and reads the signature back into OUT/sig/. check compares the
results against the same rules as the simulator tests (test_soc_isa.py, run_vtests.py).
"""
import argparse
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
LINK = HERE / "vtest_link.ld"
ISA = "rv32imafd_zve32f_zvl512b"
OUT = Path(os.environ.get("BOARD_TESTS_DIR", "/mnt/d/ScratchGPU_Vivado/board_tests"))
DDR = 0x20000000 - 0x80000000          # Synapse physical 0x8000_0000 = DDR 0x2000_0000
ISA_PAT = re.compile(r"^rv32(ui|um|ua|uf|ud|si|mi)-[pv]-\w+$")
SKIP = {"ma_data"}                      # same as test_soc_isa.py
APPROX = {"fdiv"}                       # FAST_DIV=1: expected to fail (approximate divider)


def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def symbols(elf):
    return {l.split()[2]: int(l.split()[0], 16)
            for l in sh(["riscv64-unknown-elf-nm", str(elf)]).stdout.splitlines() if len(l.split()) == 3}


def to_bin(elf, binf):
    # objcopy leaves out .bss, which the simulator's memory model starts as zero. The board's DDR
    # holds whatever the previous test left there (the -v tests keep their page tables in .bss),
    # so the image is zero-filled to the end of the last allocated section (.sbss comes after _end).
    sh(["riscv64-unknown-elf-objcopy", "-O", "binary", str(elf), str(binf)])
    data = binf.read_bytes()
    end = 0
    for l in sh(["riscv64-unknown-elf-readelf", "-S", "-W", str(elf)]).stdout.splitlines():
        m = re.search(r"\]\s+\S+\s+\S+\s+([0-9a-f]{8})\s+[0-9a-f]+\s+([0-9a-f]+)\s+\S+\s+(\S*A\S*)\s", l)
        if m and int(m.group(1), 16) >= 0x80000000:
            end = max(end, int(m.group(1), 16) + int(m.group(2), 16) - 0x80000000)
    data += b"\0" * max(0, end - len(data))
    binf.write_bytes(data + b"\0" * (-len(data) % 4))


def prep_isa(elf):
    name = elf.name
    to_bin(elf, OUT / "img" / f"{name}.bin")
    return dict(name=name, tohost=symbols(elf)["tohost"] + DDR, sig=0, words=0, timeout=5000)


def prep_vec(tag, seed, classes, irq):
    d = OUT / "build" / f"{tag}_{seed}"
    d.mkdir(parents=True, exist_ok=True)
    src, elf = d / "t.S", d / "t.elf"
    sh([sys.executable, str(HERE / "vgen.py"), "--seed", str(seed), "--out", str(src),
        "--classes", classes, "--blocks", "12", "--ops", "6"] + (["--irq"] if irq else []))
    r = sh(["riscv64-unknown-elf-gcc", f"-march={ISA}", "-mabi=ilp32", "-nostdlib", "-T", str(LINK),
            str(src), "-o", str(elf)])
    if r.returncode:
        raise RuntimeError(f"{tag} seed {seed}: build failed\n{r.stderr[-800:]}")
    nm = symbols(elf)
    ref = OUT / "ref" / f"{tag}_{seed}.sig"
    r = sh(["spike", f"--isa={ISA}", f"+signature={ref}", "--signature-granularity=4", str(elf)], timeout=120)
    if r.returncode:
        raise RuntimeError(f"{tag} seed {seed}: spike failed\n{r.stderr[-800:]}")
    to_bin(elf, OUT / "img" / f"{tag}_{seed}.bin")
    b, e = nm["begin_signature"], nm["end_signature"]
    return dict(name=f"{tag}_{seed}", tohost=nm["tohost"] + DDR, sig=b + DDR, words=(e - b) // 4,
                timeout=10000)


def seed_range(s):
    lo, _, hi = s.partition("-")
    return range(int(lo), int(hi or lo) + 1) if s else range(0)


def prepare(a):
    for sub in ("img", "ref", "sig", "build"):
        (OUT / sub).mkdir(parents=True, exist_ok=True)
        for p in (OUT / sub).glob("*.*"):
            p.unlink()
    tests = []
    isa_dir = Path(os.environ.get("RISCV_TESTS_DIR", str(Path.home() / "opt/riscv-tests/isa")))
    if not a.no_isa:
        tests += [prep_isa(f) for f in sorted(isa_dir.iterdir())
                  if ISA_PAT.match(f.name) and f.name.split("-")[-1] not in SKIP]
    jobs = [(c, s, c, False) for c in a.classes.split(",") if c for s in seed_range(a.seeds)]
    jobs += [("irq", s, "int,mask,perm,red,widen,mem,fp,sfp", True) for s in seed_range(a.irq_seeds)]
    with ThreadPoolExecutor(a.jobs) as ex:
        tests += list(ex.map(lambda j: prep_vec(*j), jobs))
    with open(OUT / "manifest.tcl", "w") as f:
        f.write("# Generated by cpu/tools/board_tests.py: name tohost_ddr sig_ddr sig_words timeout_ms\n")
        f.write("set tests {\n")
        for t in tests:
            f.write(f"    {{{t['name']} 0x{t['tohost']:08x} 0x{t['sig']:08x} {t['words']} {t['timeout']}}}\n")
        f.write("}\n")
    print(f"{len(tests)} tests prepared in {OUT}")


def check(a):
    res = OUT / "results.txt"
    if not res.exists():
        sys.exit(f"{res} not found: run run_board_tests.tcl first")
    passed, xfail, bad = 0, 0, []
    for line in res.read_text().split("\n"):
        f = line.split()
        if len(f) < 3:
            continue
        name, status, tohost = f[0], f[1], int(f[2], 16)
        expect_fail = ISA_PAT.match(name) and name.split("-")[-1] in APPROX
        ok = status == "DONE" and tohost == 1
        if ok and (OUT / "ref" / f"{name}.sig").exists():
            ref = (OUT / "ref" / f"{name}.sig").read_text().split()
            sigf = OUT / "sig" / f"{name}.bin"
            raw = sigf.read_bytes() if sigf.exists() else b""
            dut = ["%08x" % int.from_bytes(raw[i:i + 4], "little") for i in range(0, len(raw), 4)]
            if ref != dut:
                diffs = [i for i, (x, y) in enumerate(zip(ref, dut)) if x != y]
                info = f"{len(diffs)} words differ" + (f", first at +{4 * diffs[0]:#x}: ref {ref[diffs[0]]} board {dut[diffs[0]]}"
                                                       if diffs else f" (length {len(dut)} vs {len(ref)})")
                ok, status = False, "MISMATCH " + info
        if expect_fail:
            if ok:
                bad.append(f"{name}: XPASS (expected to fail with FAST_DIV=1)")
            else:
                xfail += 1
        elif ok:
            passed += 1
        else:
            bad.append(f"{name}: {status} tohost=0x{tohost:x}")
    for b in bad:
        print(b)
    print(f"{passed} passed, {xfail} expected failures (fdiv, FAST_DIV=1), {len(bad)} failed")
    sys.exit(1 if bad else 0)


def main():
    ap = argparse.ArgumentParser()
    sp = ap.add_subparsers(dest="cmd", required=True)
    p = sp.add_parser("prepare")
    p.add_argument("--seeds", default="0-24", help="vector-test seeds per class")
    p.add_argument("--classes", default="int,mask,perm,red,widen,mem,fp,sfp")
    p.add_argument("--irq-seeds", default="0-24", help="seeds with random timer interrupts")
    p.add_argument("--no-isa", action="store_true", help="skip riscv-tests")
    p.add_argument("--jobs", type=int, default=12)
    sp.add_parser("check")
    a = ap.parse_args()
    prepare(a) if a.cmd == "prepare" else check(a)


if __name__ == "__main__":
    main()
