#!/usr/bin/env python3
"""Generate cpu/rtl/include/fp_seed_rom.vh: the seed table of gpu/rtl/fp_rcpdiv.v.

4096 x 18-bit entries, value = round(seed * 2^18):
  addr[11] = 0 : 1/b       at the midpoint of 2048 segments of b in [1, 2)
  addr[11] = 1 : 1/sqrt(u) at the midpoint of 1024 segments of u in [1, 2) (addr[10] = 0)
                                                     or of u in [2, 4) (addr[10] = 1)
Every seed is within 2^-12 (relative) of the exact value anywhere in its segment.
"""
from pathlib import Path

out = Path(__file__).resolve().parent.parent / "cpu/rtl/include/fp_seed_rom.vh"
lines = ["// Generated by tools/gen_fp_seed_rom.py: do not edit. Included inside fp_rcpdiv.",
         "initial begin"]
for a in range(4096):
    if a < 2048:
        v = 1.0 / (1.0 + (a + 0.5) / 2048)
    else:
        odd, j = (a >> 10) & 1, a & 1023
        v = ((1.0 + (j + 0.5) / 1024) * (2 if odd else 1)) ** -0.5
    e = round(v * (1 << 18))
    assert 0 < e < (1 << 18)
    lines.append(f"    seed_rom[{a}] = 18'h{e:05x};")
lines.append("end")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out}")
